version: '3.4'

services:
  flask-wikiora:
    build: ./www/python/src
    ports:
      - "6497:5000"
    volumes:
      - ./www/python/src:/app
    environment:
      FLASK_APP: app.py
    restart: always
