version: '3.4'

services:
  flask-app:
    build: ./www/python/src
    ports:
      - "5000:5000"
    volumes:
      - ./www/python/src:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    restart: always
